package publishedfile

// EPublishedFileQueryType see https://partner.steamgames.com/doc/webapi/IPublishedFileService#EPublishedFileQueryType
type EPublishedFileQueryType = uint

const (
	k_PublishedFileQueryType_RankedByVote EPublishedFileQueryType = iota
	k_PublishedFileQueryType_RankedByPublicationDate
	k_PublishedFileQueryType_AcceptedForGameRankedByAcceptanceDate
	k_PublishedFileQueryType_RankedByTrend
	k_PublishedFileQueryType_FavoritedByFriendsRankedByPublicationDate
	k_PublishedFileQueryType_CreatedByFriendsRankedByPublicationDate
	k_PublishedFileQueryType_RankedByNumTimesReported
	k_PublishedFileQueryType_CreatedByFollowedUsersRankedByPublicationDate
	k_PublishedFileQueryType_NotYetRated
	k_PublishedFileQueryType_RankedByTotalUniqueSubscriptions
	k_PublishedFileQueryType_RankedByTotalVotesAsc
	k_PublishedFileQueryType_RankedByVotesUp
	k_PublishedFileQueryType_RankedByTextSearch
	k_PublishedFileQueryType_RankedByPlaytimeTrend
	k_PublishedFileQueryType_RankedByTotalPlaytime
	k_PublishedFileQueryType_RankedByAveragePlaytimeTrend
	k_PublishedFileQueryType_RankedByLifetimeAveragePlaytime
	k_PublishedFileQueryType_RankedByPlaytimeSessionsTrend
	k_PublishedFileQueryType_RankedByLifetimePlaytimeSessions
	k_PublishedFileQueryType_RankedByInappropriateContentRating
	k_PublishedFileQueryType_RankedByBanContentCheck
	k_PublishedFileQueryType_RankedByLastUpdatedDate
)

// EPublishedFileInfoMatchingFileType see https://partner.steamgames.com/doc/webapi/IPublishedFileService#EPublishedFileInfoMatchingFileType
type EPublishedFileInfoMatchingFileType = uint

const (
	k_PFI_MatchingFileType_Items EPublishedFileInfoMatchingFileType = iota
	k_PFI_MatchingFileType_Collections
	k_PFI_MatchingFileType_Art
	k_PFI_MatchingFileType_Videos
	k_PFI_MatchingFileType_Screenshots
	k_PFI_MatchingFileType_CollectionEligible
	k_PFI_MatchingFileType_Games
	k_PFI_MatchingFileType_Software
	k_PFI_MatchingFileType_Concepts
	k_PFI_MatchingFileType_GreenlightItems
	k_PFI_MatchingFileType_AllGuides
	k_PFI_MatchingFileType_WebGuides
	k_PFI_MatchingFileType_IntegratedGuides
	k_PFI_MatchingFileType_UsableInGame
	k_PFI_MatchingFileType_Merch
	k_PFI_MatchingFileType_ControllerBindings
	k_PFI_MatchingFileType_SteamworksAccessInvites
	k_PFI_MatchingFileType_Items_Mtx
	k_PFI_MatchingFileType_Items_ReadyToUse
	k_PFI_MatchingFileType_WorkshopShowcase
	k_PFI_MatchingFileType_GameManagedItems
)
